# Generated by Django 5.0.3 on 2025-10-28 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('pesan', models.TextField(verbose_name='Pesan')),
                ('tgl', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('unread', 'Belum Dibaca'), ('read', 'Sudah Dibaca')], default='unread', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notif',
                'ordering': ['-tgl'],
            },
        ),
    ]
