# Generated by Django 5.0.3 on 2025-11-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Kos')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_kos', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Kos',
                'verbose_name_plural': 'Kos',
                'db_table': 'kos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=10, verbose_name='Nomor Kamar')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('occupied', 'Ditempati'), ('maintenance', 'Perbaikan')], default='available', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('kos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.kos', verbose_name='Kos')),
                ('penyewa', models.ForeignKey(blank=True, limit_choices_to={'role': 'penyewa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Kamar',
                'db_table': 'rooms',
                'unique_together': {('kos', 'nomor_kamar')},
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('harga_bulanan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Bulanan')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Kadaluarsa'), ('terminated', 'Dihentikan')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('penyewa', models.ForeignKey(blank=True, limit_choices_to={'role': 'penyewa'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rooms.room', verbose_name='Kamar')),
            ],
            options={
                'verbose_name': 'Penyewaan',
                'verbose_name_plural': 'Penyewaan',
                'db_table': 'rentals',
            },
        ),
    ]
