# Generated by Django 5.0.3 on 2025-11-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Invoice')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('invoice_start_date', models.DateField(blank=True, null=True, verbose_name='Awal Periode Tagihan')),
                ('invoice_end_date', models.DateField(blank=True, null=True, verbose_name='Akhir Periode Tagihan')),
                ('tenggat', models.DateField(blank=True, null=True, verbose_name='Tanggal Jatuh Tempo')),
                ('status', models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Lunas'), ('overdue', 'Telat Bayar'), ('cancelled', 'Batal Membayar')], default='unpaid', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('penyewa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rooms.rental', verbose_name='Penyewaan')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('pembayaran_id', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_bayar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Bayar')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('tenggat', models.DateField(blank=True, null=True, verbose_name='Tanggal Jatuh Tempo')),
                ('metode', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('e_wallet', 'Dompet Digital')], max_length=20, verbose_name='Metode Pembayaran')),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('completed', 'Selesai'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaksi')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bukti Pembayaran')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Diverifikasi pada')),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='rooms.room', verbose_name='Kamar')),
                ('penyewa', models.ForeignKey(limit_choices_to={'role': 'penyewa'}, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pembayaran', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'db_table': 'pembayaran',
                'ordering': ['-tgl_bayar'],
            },
        ),
        migrations.CreateModel(
            name='LaporanKeuangan',
            fields=[
                ('laporan_id', models.AutoField(primary_key=True, serialize=False)),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=20, verbose_name='Bulan')),
                ('tahun', models.IntegerField(default=2025, verbose_name='Tahun')),
                ('total_pemasukan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Pemasukan')),
                ('total_pengeluaran', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Pengeluaran')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_keuangan', to=settings.AUTH_USER_MODEL, verbose_name='Admin Pembuat')),
            ],
            options={
                'verbose_name': 'Laporan Keuangan',
                'verbose_name_plural': 'Laporan Keuangan',
                'db_table': 'laporan_keuangan',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('bulan', 'tahun')},
            },
        ),
    ]
