# Generated by Django 5.0.3 on 2025-12-23 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporankeuangan',
            options={'ordering': ['-bulan'], 'verbose_name': 'Laporan Keuangan', 'verbose_name_plural': 'Laporan Keuangan'},
        ),
        migrations.AlterUniqueTogether(
            name='laporankeuangan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_end_date',
            field=models.DateField(blank=True, db_column='billing_period_end', null=True, verbose_name='Akhir Periode Tagihan'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_start_date',
            field=models.DateField(blank=True, db_column='billing_period_start', null=True, verbose_name='Awal Periode Tagihan'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='penyewa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenggat',
            field=models.DateField(blank=True, db_column='due_date', null=True, verbose_name='Tanggal Jatuh Tempo'),
        ),
        migrations.AlterField(
            model_name='laporankeuangan',
            name='bulan',
            field=models.DateField(verbose_name='Bulan'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='metode',
            field=models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('e_wallet', 'Dompet Digital'), ('midtrans', 'Midtrans')], max_length=20, verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='penyewa',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'penyewa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa'),
        ),
        migrations.RemoveField(
            model_name='laporankeuangan',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='laporankeuangan',
            name='user',
        ),
    ]
