# Generated by Django 5.0.3 on 2025-11-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('penyewa', models.ForeignKey(blank=True, limit_choices_to={'role': 'penyewa'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cards', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to='rooms.room')),
            ],
            options={
                'db_table': 'rfid_cards',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], max_length=20)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='rooms.room')),
                ('rfid_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='rfid.rfidcard')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-access_time'],
            },
        ),
    ]
