# Generated by Django 5.0.3 on 2025-11-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kerusakan',
            fields=[
                ('laporan_id', models.AutoField(primary_key=True, serialize=False)),
                ('deskripsi', models.TextField(help_text='Jelaskan kerusakan dengan detail', verbose_name='Deskripsi')),
                ('tgl_lapor', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Lapor')),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('in_progress', 'Sedang Dikerjakan'), ('resolved', 'Selesai'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Mendesak')], default='medium', max_length=20, verbose_name='Prioritas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='damage_images/', verbose_name='Gambar')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Penyelesaian')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Diselesaikan pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kerusakan', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan ke')),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kerusakan', to='rooms.room', verbose_name='Kamar')),
                ('penyewa', models.ForeignKey(limit_choices_to={'role': 'penyewa'}, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kerusakan', to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
            ],
            options={
                'verbose_name': 'Kerusakan',
                'verbose_name_plural': 'Kerusakan',
                'db_table': 'kerusakan',
                'ordering': ['-tgl_lapor'],
            },
        ),
    ]
